### ISSUE TITLE
KeyError: "No object named 'JitterCrop' found in 'transforms' registry!"

### ISSUE THREAD

**Issue by serser** [megvii-model/YOLOF#21]
Env:

1. **OS version**：CentOS 7
2. **Environment version:**   Python 3.6.13 / PyTorch 1.8.0 / CUDA 11.0 / cuDNN version
3. **cvpods version**：commit id : 82374a1fe5c83e16bdd4d07adae2545d51138ef8_

I ran the following command：
```bash

cd playground/detection/coco/yolof/yolof.cspdarknet53.DC5.3x
pods_train --num-gpus 8

```

Actual results：
```

Traceback (most recent call last):
  File "/ssd/serser/cvpods/tools/train_net.py", line 109, in <module>
    args=(args,),
  File "/ssd/serser/cvpods/cvpods/engine/launch.py", line 53, in launch
    daemon=False,
  File "/ssd/serser/venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/ssd/serser/venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/ssd/serser/venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/ssd/serser/venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/ssd/serser/cvpods/cvpods/engine/launch.py", line 88, in _distributed_worker
    main_func(*args)
  File "/ssd/serser/cvpods/tools/train_net.py", line 74, in main
    runner = runner_decrator(RUNNERS.get(cfg.TRAINER.NAME))(cfg, build_model)
  File "/ssd/serser/cvpods/cvpods/engine/runner.py", line 86, in __init__
    self.data_loader = self.build_train_loader(cfg)
  File "/ssd/serser/cvpods/cvpods/engine/runner.py", line 307, in build_train_loader
    return build_train_loader(cfg)
  File "/ssd/serser/cvpods/cvpods/data/build.py", line 130, in build_train_loader
    transform_gens = build_transform_gens(cfg.INPUT.AUG.TRAIN_PIPELINES)
  File "/ssd/serser/cvpods/cvpods/data/build.py", line 69, in build_transform_gens
    return build(pipelines)
  File "/ssd/serser/cvpods/cvpods/data/build.py", line 58, in build
    tfm = TRANSFORMS.get(aug)(**args)
  File "/ssd/serser/cvpods/cvpods/utils/registry.py", line 66, in get
    "No object named '{}' found in '{}' registry!".format(name, self._name)
KeyError: "No object named 'JitterCrop' found in 'transforms' registry!"

```

**Comment by serser** [comment]
Turns out I am using official `cvpods` instead of `yolof/cvpods`.

**Comment by Lixia1221** [comment]
> Turns out I am using official `cvpods` instead of `yolof/cvpods`.

I have replaced it but still reported wrong
