### ISSUE TITLE
KeyError: "No object named 'RandomShift' found in 'transforms' registry!"

### ISSUE THREAD

**Issue by wanghangege** [megvii-model/YOLOF#22]
[04/14 13:57:07 c2.utils.env.env]: Using a generated random seed 7889427
Traceback (most recent call last):
  File "/media/ubun/CC7251E47251D3B4/yoloseries/YOLOF-main/tools/train_net.py", line 109, in <module>
    args=(args,),
  File "/home/ubun/cvpods/cvpods/engine/launch.py", line 53, in launch
    daemon=False,
  File "/home/ubun/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ubun/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/ubun/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubun/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/ubun/cvpods/cvpods/engine/launch.py", line 88, in _distributed_worker
    main_func(*args)
  File "/media/ubun/CC7251E47251D3B4/yoloseries/YOLOF-main/tools/train_net.py", line 74, in main
    runner = runner_decrator(RUNNERS.get(cfg.TRAINER.NAME))(cfg, build_model)
  File "/home/ubun/cvpods/cvpods/engine/runner.py", line 86, in __init__
    self.data_loader = self.build_train_loader(cfg)
  File "/home/ubun/cvpods/cvpods/engine/runner.py", line 307, in build_train_loader
    return build_train_loader(cfg)
  File "/home/ubun/cvpods/cvpods/data/build.py", line 130, in build_train_loader
    transform_gens = build_transform_gens(cfg.INPUT.AUG.TRAIN_PIPELINES)
  File "/home/ubun/cvpods/cvpods/data/build.py", line 69, in build_transform_gens
    return build(pipelines)
  File "/home/ubun/cvpods/cvpods/data/build.py", line 58, in build
    tfm = TRANSFORMS.get(aug)(**args)
  File "/home/ubun/cvpods/cvpods/utils/registry.py", line 66, in get
    "No object named '{}' found in '{}' registry!".format(name, self._name)
KeyError: "No object named 'RandomShift' found in 'transforms' registry!"

**Comment by chensnathan** [comment]
Hi, you can refer to #21 for the solution. 

BTW, we have updated the guidance of how to install `YOLOF/cvpods`, you can follow the steps in the README.
